name: hypoc
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bottleneck=1.3.5
  - ca-certificates=2023.7.22
  - cudatoolkit=11.3.1
  - freetype=2.12.1
  - giflib=5.2.1
  - intel-openmp=2023.1.0
  - jpeg=9b
  - lcms2=2.12
  - libffi=3.4.4
  - libpng=1.6.39
  - libtiff=4.1.0
  - libuv=1.44.2
  - libwebp=1.2.0
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ninja=1.10.2
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.11
  - pandas=2.0.3
  - pillow=9.3.0
  - pip=23.2.1
  - python=3.8.18
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - typing_extensions=4.7.1
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
    - ansible==6.7.0
    - ansible-core==2.13.12
    - certifi==2023.7.22
    - cffi==1.16.0
    - charset-normalizer==3.3.1
    - cryptography==41.0.4
    - idna==3.4
    - imageio==2.31.6
    - jinja2==3.1.2
    - joblib==1.3.2
    - lazy-loader==0.3
    - markupsafe==2.1.3
    - networkx==3.1
    - opencv-python==4.8.1.78
    - packaging==23.2
    - pycparser==2.21
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - requests==2.31.0
    - resolvelib==0.8.1
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - threadpoolctl==3.2.0
    - tifffile==2023.7.10
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - torch==1.12.1+cu113
    - torchaudio==0.12.1+cu113
    - torchvision==0.13.1+cu113
    - tqdm==4.66.1
    - urllib3==2.0.5